name: myconda
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - pytorch
  - torchaudio
  - torchvision
  - cpuonly
  - numpy
  - scikit-learn
  - pillow
  - psutil
  - einops
  - pandas
  - tqdm
  - simplejson
  - flask
  - celery
  - gevent
  - timm
  - pip:
      - gunicorn
      - redis
      - supervisor
      - opencv-python-headless